'use client';
import { driveFailure } from '../lib/drive';
import {useState,useEffect,useLayoutEffect,useRef,useCallback,memo} from 'react';
import {BookOpen,ArrowUpRight,Headphones,Play,Pause,RotateCcw,RotateCw,List,ChevronLeft,ChevronRight,Check,LoaderCircle,PanelTop,ChevronDown} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {ToggleGroup,ToggleGroupItem} from '@/components/ui/toggle-group';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';
import {catalog,assetURL,type BookMetadata} from '@/lib/catalog';
import {Book,floorIndex,clock,storageKey,readSaved,saveProgress} from '@/lib/reader';
const bookPromises=new Map<string,Promise<Book>>();
function loadBook(metadata:BookMetadata){let promise=bookPromises.get(metadata.id);if(!promise){promise=fetch(assetURL(metadata.id,'prepared')).then(async r=>{if(!r.ok)throw Error(await driveFailure(r,'The book could not load from Google Drive.'));const bytes=await r.arrayBuffer();const source=new Uint8Array(bytes);const gzip=source[0]===31&&source[1]===139;const body=gzip?new Response(new Blob([source]).stream().pipeThrough(new DecompressionStream('gzip'))):new Response(source);const b=await body.json() as Book;if(b.version!==1||b.id!==metadata.id||b.chapters.length!==metadata.chapters.length)throw Error('The book data could not be read.');return b}).catch(e=>{bookPromises.delete(metadata.id);throw e});bookPromises.set(metadata.id,promise)}return promise}
export default function Home(){
 const [selected,setSelected]=useState<string|null>(null),[revision,setRevision]=useState(0),[storageAvailable,setStorageAvailable]=useState(true);
 useEffect(()=>{try{const key='whisperbook.storage-check';localStorage.setItem(key,'1');localStorage.removeItem(key)}catch{setStorageAvailable(false)}},[revision]);
 useEffect(()=>{const hash=()=>{const id=location.hash==='#read'?'dungeon-crawler-carl':location.hash.startsWith('#read/')?decodeURIComponent(location.hash.slice(6)):null;setSelected(catalog.some(b=>b.id===id)?id:null);setRevision(r=>r+1)};hash();window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash)},[]);
 const open=(id:string)=>{location.hash=`read/${id}`;setSelected(id)};
 const back=()=>{history.replaceState(null,'',location.pathname);setSelected(null);setRevision(r=>r+1)};
 const metadata=catalog.find(b=>b.id===selected);
 useEffect(()=>{if(selected)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'open_book',description:'Open a book from the library.',inputSchema:{type:'object',properties:{id:{type:'string',enum:catalog.map(b=>b.id)}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{id?:string})=>{const id=input.id||'dungeon-crawler-carl';if(!catalog.some(b=>b.id===id))throw Error('Unknown book');open(id);return{book:id,view:'reader'}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[selected]);
 if(metadata)return <Reader key={metadata.id} metadata={metadata} onBack={back}/>;
 return <main className="library"><header className="site-header"><a href="./" className="brand"><BookOpen size={23}/> WhisperBook</a><span className="device-note">{storageAvailable?'Saved on this device':'Progress cannot be saved'}</span></header><section className="library-content"><div className="section-heading"><h1>Library</h1><span>{catalog.length} {catalog.length===1?'book':'books'}</span></div><div className="book-grid">{catalog.map(item=>{const saved=revision===0?null:readSaved(item.id,item.duration),position=saved?.position||0,percent=position/item.duration*100,marker=item.markers[floorIndex(item.markers,position,c=>c.start)];return <button key={item.id} className="book-card" onClick={()=>open(item.id)}><img src={item.cover} alt={`${item.title} cover`}/><div className="book-info"><h2>{item.title}</h2><p>{item.author}</p><div className="narrator"><Headphones size={16}/> {item.narrator}</div><div className="book-duration">{Math.floor(item.duration/3600)} hr {Math.floor(item.duration/60)%60} min · {item.chapterCount??item.chapters.length} chapters</div>{position>0&&<div className="saved-progress"><div><span>{marker.title}</span><span>{Math.floor(percent)}%</span></div><Progress value={percent}/></div>}<div className="read-action">{position>0?'Continue reading':'Open book'} <ArrowUpRight size={20}/></div></div></button>})}</div></section></main>
}
function Reader({metadata,onBack}:{metadata:BookMetadata;onBack:()=>void}){
 const reading=true;const [book,setBook]=useState<Book|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[buffering,setBuffering]=useState(false),[rate,setRate]=useState(1.5),[mode,setMode]=useState<'sentence'|'word'>('sentence'),[chaptersOpen,setChaptersOpen]=useState(false),[storageOK,setStorageOK]=useState(true);
 const [controlsVisible,setControlsVisible]=useState(true),[timeScope,setTimeScope]=useState<'chapter'|'book'>('chapter');
 const audioReady=useRef(false);const audio=useRef<HTMLAudioElement>(null),current=useRef({time:0,rate:1.5,mode:'sentence' as 'sentence'|'word'}),restored=useRef(false),lastSaved=useRef(0);
 const persist=useCallback(()=>{if(!restored.current)return;const s=current.current;setStorageOK(saveProgress({position:audioReady.current?(audio.current?.currentTime??s.time):s.time,rate:s.rate,highlight:s.mode,updatedAt:Date.now()},metadata.id))},[]);
 const ensureBook=useCallback(async()=>{setLoading(true);setError('');try{setBook(await loadBook(metadata))}catch(e){setError(e instanceof Error && e.message.startsWith("Google Drive's")?e.message:'The book could not load from Google Drive. Please try again.')}finally{setLoading(false)}},[]);
 useEffect(()=>{const s=readSaved(metadata.id,metadata.duration);setTime(s.position);setRate(s.rate);setMode(s.highlight);current.current={time:s.position,rate:s.rate,mode:s.highlight};restored.current=true;const flush=()=>persist();window.addEventListener('pagehide',flush);document.addEventListener('visibilitychange',flush);void ensureBook();return()=>{persist();window.removeEventListener('pagehide',flush);document.removeEventListener('visibilitychange',flush)}},[ensureBook,persist]);
 useEffect(()=>{current.current={time,rate,mode};if(audio.current)audio.current.playbackRate=rate},[time,rate,mode]);
 useEffect(()=>{if(restored.current)persist()},[rate,mode,persist]);
 function open(){if(!book&&!loading)void ensureBook()}
 function library(){audio.current?.pause();persist();onBack()}
 function seek(next:number){next=Math.max(0,Math.min(metadata.duration,next));current.current.time=next;setTime(next);if(audio.current)audio.current.currentTime=next;persist()}
 async function toggle(){if(!audio.current)return;if(playing)audio.current.pause();else{setError('');try{await audio.current.play()}catch{setError('Playback could not start. Tap Play to try again.')}}}
 useEffect(()=>{if(!reading)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.code!=='Space'||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||event.defaultPrevented)return;const target=event.target as HTMLElement;if(chaptersOpen||(!target.closest('.bars-toggle,.play-button')&&target.closest('input,textarea,select,button,a,[contenteditable="true"],[role="slider"],[role="combobox"],[role="dialog"],[role="menu"]')))return;event.preventDefault();if(event.repeat)return;setControlsVisible(true);if(!book||error||!audio.current)return;if(!audio.current.paused)audio.current.pause();else{setError('');void audio.current.play().catch(()=>setError('Playback could not start. Tap Play to try again.'))}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[reading,book,error,chaptersOpen]);
 const chapterIndex=book?floorIndex(book.chapters,time,c=>c.start):0;
 const markerIndex=floorIndex(metadata.markers,time,c=>c.start),marker=metadata.markers[markerIndex];
 const rangeStart=timeScope==='chapter'?marker.start:0,rangeEnd=timeScope==='chapter'?marker.end:metadata.duration;
 const remaining=Math.max(0,rangeEnd-time)/rate;
 const percent=Math.min(100,time/metadata.duration*100);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const tool of [{name:'open_book',description:'Open the current book in the reader.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async(input:Record<string,unknown>)=>{if(Object.keys(input).length)throw Error('No arguments accepted');open();await new Promise(r=>setTimeout(r,0));return{book:metadata.id,view:'reader'}}},{name:'seek_book',description:'Seek the audiobook to a source-audio timestamp in seconds.',inputSchema:{type:'object',properties:{seconds:{type:'number',minimum:0,maximum:metadata.duration}},required:['seconds'],additionalProperties:false},execute:async(input:{seconds:number})=>{if(!Number.isFinite(input.seconds)||input.seconds<0||input.seconds>metadata.duration)throw Error('Invalid seconds');seek(input.seconds);await new Promise(r=>setTimeout(r,0));return{seconds:input.seconds}}}]){try{Promise.resolve(context.registerTool({...tool,annotations:{readOnlyHint:false}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort()},[book]);
 return <>
 <audio ref={audio} crossOrigin="anonymous" src={assetURL(metadata.id,'audio')} preload="metadata" onEmptied={()=>{audioReady.current=false}} onLoadedMetadata={()=>{if(audio.current){audio.current.currentTime=current.current.time;audio.current.playbackRate=rate;audioReady.current=true}}} onTimeUpdate={()=>{if(!reading||!audioReady.current)return;const t=audio.current?.currentTime||0;current.current.time=t;setTime(t);if(Date.now()-lastSaved.current>2000){persist();lastSaved.current=Date.now()}}} onPlay={()=>setPlaying(true)} onPause={()=>{setPlaying(false);persist()}} onWaiting={()=>setBuffering(true)} onPlaying={()=>setBuffering(false)} onCanPlay={()=>setBuffering(false)} onEnded={()=>{setPlaying(false);persist()}} onError={()=>{if(reading)setError('Audio could not load from Google Drive. Try again.')}}/>
 <main className={`reader-shell ${controlsVisible?'':'controls-hidden'}`}><header className="reader-header"><button aria-label="Library" className="back-button" onClick={library}><ChevronLeft size={24}/><span>Library</span></button><div className="reader-book-title">{metadata.title}<span>{metadata.author}</span></div><Sheet open={chaptersOpen} onOpenChange={setChaptersOpen}><SheetTrigger aria-label="Chapters" className="chapters-trigger"><List size={19}/><span>Chapters</span></SheetTrigger><SheetContent side="right" className="chapter-sheet"><SheetHeader><SheetTitle>Chapters</SheetTitle></SheetHeader><nav className="chapter-list">{metadata.markers.map((c,i)=><button key={i} className={i===markerIndex?'selected':''} onClick={()=>{seek(c.start);setChaptersOpen(false)}}><span>{c.title}</span><span>{i===markerIndex?<Headphones size={15}/>:clock(c.start)}</span></button>)}</nav></SheetContent></Sheet></header>
 <div className="reader-toolbar"><span className="chapter-label">{marker.title}</span><div className="highlight-controls"><span>Highlight</span><ToggleGroup value={[mode]} onValueChange={v=>{if(v[0]==='word'||v[0]==='sentence')setMode(v[0])}} className="highlight-toggle" aria-label="Highlight mode"><ToggleGroupItem value="sentence" aria-label="Sentence highlighting">Sentence</ToggleGroupItem><ToggleGroupItem value="word" aria-label="Word highlighting">Word</ToggleGroupItem></ToggleGroup></div></div>
 <div className="reading-area">{error&&!book?<div role="alert" className="reader-message"><p>{error}</p><button onClick={()=>{setError('');audio.current?.load();void ensureBook()}}>Try again</button></div>:loading||!book?<div className="reader-message" role="status"><LoaderCircle className="spin"/><p>Loading book…</p></div>:<ReadingPage coverURL={metadata.cover} book={book} chapterIndex={chapterIndex} time={time} mode={mode} playing={playing} audio={audio} seek={seek} controlsVisible={controlsVisible} toggleControls={()=>setControlsVisible(v=>!v)}/>}</div>
 {error&&book&&<div role="alert" className="playback-error"><span>{error}</span><button onClick={()=>{setError('');setBuffering(false);audio.current?.load()}}>Try again</button></div>}
 <footer className="player"><div className="timeline"><span>{clock(time-rangeStart)}</span><Slider aria-label={timeScope==='chapter'?'Chapter position':'Book position'} min={rangeStart} max={rangeEnd} step={1} value={[time]} onValueChange={v=>seek(Array.isArray(v)?v[0]:v)} /><span className="remaining-time">{clock(remaining)} left</span></div><div className="player-controls"><div className="playback-meta"><button className="time-scope" aria-label={timeScope==='chapter'?'Show book remaining time':'Show chapter remaining time'} onClick={()=>setTimeScope(v=>v==='chapter'?'book':'chapter')}>{timeScope==='chapter'?'Chapter':'Book'}<ChevronDown size={13}/></button><span>{timeScope==='chapter'?marker.title:`${Math.floor(percent)}% complete`}</span></div><div className="transport"><button onClick={()=>seek(time-15)} aria-label="Back 15 seconds" className="skip"><RotateCcw size={24}/><small>15</small></button><button className="play-button" aria-keyshortcuts="Space" onClick={toggle} aria-label={playing?'Pause':'Play'} disabled={!book||!!error}>{buffering&&playing?<LoaderCircle size={25} className="spin"/>:playing?<Pause size={25} fill="currentColor"/>:<Play size={25} fill="currentColor"/>}</button><button onClick={()=>seek(time+15)} aria-label="Forward 15 seconds" className="skip"><RotateCw size={24}/><small>15</small></button></div><div className="speed-control"><Select value={String(rate)} onValueChange={v=>setRate(Number(v))}><SelectTrigger aria-label="Playback speed"><SelectValue>{rate}×</SelectValue></SelectTrigger><SelectContent>{[.75,1,1.25,1.5,1.75,2].map(r=><SelectItem key={r} value={String(r)}>{r}×</SelectItem>)}</SelectContent></Select><span className="save-state">{storageOK?<><Check size={13}/> Saved</>:'Not saved'}</span></div></div></footer></main>
 </>
}
function ReadingPage({coverURL,book,chapterIndex,time,mode,playing,audio,seek,controlsVisible,toggleControls}:{coverURL:string;controlsVisible:boolean;toggleControls:()=>void;book:Book;chapterIndex:number;time:number;mode:'sentence'|'word';playing:boolean;audio:React.RefObject<HTMLAudioElement|null>;seek:(t:number)=>void}){
 const viewport=useRef<HTMLDivElement>(null),article=useRef<HTMLElement>(null),geometry=useRef<{nodes:HTMLElement[];pages:number[];starts:number[];width:number}>({nodes:[],pages:[],starts:[],width:0});const [page,setPage]=useState(0),[pageCount,setPageCount]=useState(1),[layout,setLayout]=useState(0);const chapter=book.chapters[chapterIndex];const cover=time>=book.creditsStart;const introduction=Boolean(book.audioOnlyIntroduction&&time<book.introEnd);
 useLayoutEffect(()=>{const el=article.current,view=viewport.current;if(!el||!view)return;let timer:ReturnType<typeof setTimeout>;function measure(){if(!el||!view)return;el.style.transition='none';el.style.transform='none';const width=view.clientWidth;el.style.columnWidth=`${width}px`;const nodes=Array.from(el.querySelectorAll<HTMLElement>('.word'));const base=el.getBoundingClientRect().left;const pages=nodes.map(n=>Math.max(0,Math.floor((n.getBoundingClientRect().left-base+1)/(width+64))));const starts:number[]=[];pages.forEach((p,i)=>{if(starts[p]===undefined)starts[p]=i});geometry.current={nodes,pages,starts,width};setPageCount(Math.max(1,starts.length));setLayout(n=>n+1)}measure();const observer=new ResizeObserver(()=>{clearTimeout(timer);timer=setTimeout(measure,50)});observer.observe(view);return()=>{observer.disconnect();clearTimeout(timer)}},[chapter]);
 useEffect(()=>{let frame=0,lastWord=-1,lastSentence=-1,lastPage=-1;const el=article.current;if(!el)return;const g=geometry.current;const update=()=>{const t=playing?(audio.current?.currentTime??time):time;const word=floorIndex(chapter.cues,t,c=>c[0]);let p=g.pages[word]||0;const next=g.starts[p+1];if(playing&&next!==undefined&&chapter.cues[next][0]-t<=.18*(audio.current?.playbackRate||1))p++;
 if(lastPage!==p){el.style.transition=playing?'transform 180ms ease-out':'none';el.style.transform=`translateX(${-p*(g.width+64)}px)`;setPage(p);lastPage=p}
 if(chapter.spoken===false||t<chapter.cues[0][0]||t>=book.creditsStart){(CSS as any).highlights?.delete('sentence');(CSS as any).highlights?.delete('spoken');el.querySelectorAll('.active-word').forEach(n=>n.classList.remove('active-word'));el.dataset.activeWord='-1';el.dataset.cueTime=String(t);lastWord=-1;lastSentence=-1;if(playing)frame=requestAnimationFrame(update);return}
 el.dataset.activeWord=String(word);el.dataset.connected=String(g.nodes[word]?.isConnected);el.dataset.cueTime=String(t);const si=floorIndex(chapter.sentences,word,s=>s[0]);if(lastWord!==word||lastSentence!==si){const css=CSS as any;if(css.highlights){if(mode==='word'){const n=g.nodes[word];if(n){const r=new Range();r.selectNodeContents(n);css.highlights.set('spoken',new (window as any).Highlight(r));css.highlights.delete('sentence')}}else{const [a,b]=chapter.sentences[si];const first=g.nodes[a],last=g.nodes[b-1];if(first&&last){const r=new Range();r.setStartBefore(first);const next=g.nodes[b];if(next&&last.closest('p,li,blockquote,h1,h2,h3')===next.closest('p,li,blockquote,h1,h2,h3'))r.setEndBefore(next);else{const block=last.closest('p,li,blockquote,h1,h2,h3');if(block)r.setEnd(block,block.childNodes.length);else r.setEndAfter(last)}css.highlights.set('sentence',new (window as any).Highlight(r));css.highlights.delete('spoken')}}}else{el.querySelectorAll('.active-word').forEach(n=>n.classList.remove('active-word'));const [a,b]=mode==='word'?[word,word+1]:chapter.sentences[si];for(let i=a;i<b;i++)g.nodes[i]?.classList.add('active-word')};lastWord=word;lastSentence=si}if(playing)frame=requestAnimationFrame(update)};update();return()=>{cancelAnimationFrame(frame);(CSS as any).highlights?.delete('sentence');(CSS as any).highlights?.delete('spoken')}},[chapter,time,mode,playing,layout,audio,book.creditsStart]);
 function turn(delta:number){if(introduction){if(delta>0)seek(book.chapters[0].start);return}const target=page+delta;const start=geometry.current.starts[target];if(start!==undefined)seek(chapter.cues[start][0]);else if(delta<0&&chapterIndex>0)seek(book.chapters[chapterIndex-1].start);else if(delta>0&&chapterIndex<book.chapters.length-1)seek(book.chapters[chapterIndex+1].start)}
 function seekWord(event:React.MouseEvent){const word=(event.target as HTMLElement).closest<HTMLElement>('[data-word]');if(!word||!article.current?.contains(word))return;const index=Number(word.dataset.word);if(chapter.cues[index])seek(chapter.cues[index][0]);}
 return <div className="page-layout" onClick={event=>{const target=event.target as HTMLElement;if(target.closest('[data-word],button,a,input,[role="button"]')||window.getSelection()?.toString())return;toggleControls()}}><div onClick={seekWord} className="paper-window" ref={viewport} style={{visibility:cover||introduction?'hidden':'visible'}}><BookText ref={article} html={chapter.html}/></div>{introduction&&<div className="cover-page" role="status"><span>Audio-only introduction</span></div>}{cover&&<div className="cover-page"><img src={coverURL} alt={`${book.title} cover`}/><span>{time<book.introEnd?'Opening credits':'End credits'}</span></div>}<div className="page-navigation"><button aria-label="Previous page" onClick={()=>turn(-1)} disabled={cover||introduction||(page===0&&chapterIndex===0)}><ChevronLeft size={18}/></button><span>{cover||introduction?'':`Page ${page+1} of ${pageCount}`}</span><button aria-label="Next page" onClick={()=>turn(1)} disabled={cover||(page===pageCount-1&&chapterIndex===book.chapters.length-1)}><ChevronRight size={18}/></button><button className="bars-toggle" aria-label={controlsVisible?'Hide controls':'Show controls'} aria-pressed={!controlsVisible} onClick={toggleControls}><PanelTop size={18}/><span>{controlsVisible?'Hide controls':'Show controls'}</span></button></div></div>
}

const BookText=memo(function BookText({html,ref}:{html:string;ref:React.RefObject<HTMLElement|null>}){return <article ref={ref} className="epub-page" dangerouslySetInnerHTML={{__html:html}}/>});
