'use client';
import { driveFailure, initializeDriveAudio, r2AudioBase, r2Books } from '../lib/drive';
import {DriveCover} from '@/components/drive-cover';
import {useState,useEffect,useLayoutEffect,useRef,useCallback,memo} from 'react';
import {BookOpen,ArrowUpRight,Headphones,Play,Pause,List,ChevronLeft,ChevronRight,LoaderCircle} from 'lucide-react';
import {ToggleGroup,ToggleGroupItem} from '@/components/ui/toggle-group';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';
import {catalog,assetURL,type BookMetadata} from '@/lib/catalog';
import {Book,floorIndex,clock,readSaved,saveProgress} from '@/lib/reader';
const bookPromises=new Map<string,Promise<Book>>();
function loadBook(metadata:BookMetadata){let promise=bookPromises.get(metadata.id);if(!promise){promise=fetch(assetURL(metadata.id,'prepared')).then(async r=>{if(!r.ok)throw Error(await driveFailure(r,'The book could not load from Google Drive.'));const bytes=await r.arrayBuffer();const source=new Uint8Array(bytes);const gzip=source[0]===31&&source[1]===139;const body=gzip?new Response(new Blob([source]).stream().pipeThrough(new DecompressionStream('gzip'))):new Response(source);const b=await body.json() as Book;if(b.version!==1||b.id!==metadata.id||b.chapters.length!==metadata.chapters.length)throw Error('The book data could not be read.');return b}).catch(e=>{bookPromises.delete(metadata.id);throw e});bookPromises.set(metadata.id,promise)}return promise}
export default function Home(){
 const [selected,setSelected]=useState<string|null>(null),[revision,setRevision]=useState(0),[storageAvailable,setStorageAvailable]=useState(true);
 useEffect(()=>{try{const key='whisperbook.storage-check';localStorage.setItem(key,'1');localStorage.removeItem(key)}catch{setStorageAvailable(false)}},[revision]);
 useEffect(()=>{const hash=()=>{const id=location.hash==='#read'?'dungeon-crawler-carl':location.hash.startsWith('#read/')?decodeURIComponent(location.hash.slice(6)):null;setSelected(catalog.some(b=>b.id===id)?id:null);setRevision(r=>r+1)};hash();window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash)},[]);
 const open=(id:string)=>{location.hash=`read/${id}`;setSelected(id)};
 const back=()=>{history.replaceState(null,'',location.pathname);setSelected(null);setRevision(r=>r+1)};
 const metadata=catalog.find(b=>b.id===selected);
 useEffect(()=>{if(selected)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'open_book',description:'Open a book from the library.',inputSchema:{type:'object',properties:{id:{type:'string',enum:catalog.map(b=>b.id)}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{id?:string})=>{const id=input.id||'dungeon-crawler-carl';if(!catalog.some(b=>b.id===id))throw Error('Unknown book');open(id);return{book:id,view:'reader'}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[selected]);
 if(metadata)return <Reader key={metadata.id} metadata={metadata} onBack={back}/>;
 return <main className="library"><header className="site-header"><a href="./" className="brand"><BookOpen size={23}/> WhisperBook</a><span className="device-note">{storageAvailable?'Saved on this device':'Progress cannot be saved'}</span></header><section className="library-content"><div className="section-heading"><h1>Library</h1><span>{catalog.length} {catalog.length===1?'book':'books'}</span></div><div className="book-grid">{catalog.map(item=>{const saved=revision===0?null:readSaved(item.id,item.duration),position=saved?.position||0,percent=position/item.duration*100,marker=item.markers[floorIndex(item.markers,position,c=>c.start)];return <button key={item.id} className="book-card" onClick={()=>open(item.id)}><DriveCover src={item.cover} alt={`${item.title} cover`}/><div className="book-info"><h2>{item.title}</h2><p>{item.author}</p><div className="narrator"><Headphones size={16}/> {item.narrator}</div><div className="book-duration">{Math.floor(item.duration/3600)} hr {Math.floor(item.duration/60)%60} min · {item.chapterCount??item.chapters.length} chapters</div>{position>0&&<div className="saved-progress"><div><span>{marker.title}</span><span>{Math.floor(percent)}%</span></div><Progress value={percent}/></div>}<div className="read-action">{position>0?'Continue reading':'Open book'} <ArrowUpRight size={20}/></div></div></button>})}</div></section></main>
}
function Reader({metadata,onBack}:{metadata:BookMetadata;onBack:()=>void}){
 const reading=true;const [book,setBook]=useState<Book|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[buffering,setBuffering]=useState(false),[rate,setRate]=useState(1.25),[mode,setMode]=useState<'sentence'|'word'>('word'),[chaptersOpen,setChaptersOpen]=useState(false);
 const r2Streaming=Boolean(r2Books[metadata.id]);const r2Extension=r2Books[metadata.id]?.extension||'m4a';const [audioSource,setAudioSource]=useState('');const [streamSegment,setStreamSegment]=useState(0);
 const r2Source=(index:number)=>`${r2AudioBase}/${metadata.id}/segment-${String(index).padStart(3,'0')}.${r2Extension}`;
 const audioReady=useRef(false);const audio=useRef<HTMLAudioElement>(null),current=useRef({time:0,rate:1.25,mode:'word' as 'sentence'|'word'}),pageRef=useRef({chapterIndex:0,page:0,start:0}),restored=useRef(false),lastSaved=useRef(0),streamOffset=useRef(0),pendingLocalSeek=useRef<number|null>(null),pendingPlay=useRef(false);
 useEffect(()=>{let active=true;if(r2Streaming){setAudioSource(r2Source(0));return()=>{active=false}}void initializeDriveAudio(metadata.id).then(url=>{if(active){setAudioSource(url);setError(previous=>previous.startsWith('Audio')?'':previous)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Drive streaming could not initialize.')});return()=>{active=false}},[metadata.id,r2Streaming]);
 const persist=useCallback(()=>{if(!restored.current)return;const s=current.current;const position=audioReady.current&&audio.current?audio.current.currentTime+(r2Streaming?streamOffset.current:0):s.time;saveProgress({position,rate:s.rate,highlight:s.mode,chapterIndex:pageRef.current.chapterIndex,page:pageRef.current.page,updatedAt:Date.now()},metadata.id)},[metadata.id,r2Streaming]);
 const ensureBook=useCallback(async()=>{setLoading(true);setError('');try{setBook(await loadBook(metadata))}catch(e){setError(e instanceof Error && e.message.startsWith("Google Drive's")?e.message:'The book could not load from Google Drive. Please try again.')}finally{setLoading(false)}},[]);
 useEffect(()=>{const s=readSaved(metadata.id,metadata.duration);setTime(s.position);setRate(s.rate);setMode('word');pageRef.current={chapterIndex:s.chapterIndex,page:s.page,start:s.position};current.current={time:s.position,rate:s.rate,mode:'word'};if(r2Streaming){const index=floorIndex(metadata.markers,s.position,c=>c.start),start=metadata.markers[index]?.start||0;streamOffset.current=start;pendingLocalSeek.current=s.position-start;setStreamSegment(index);setAudioSource(r2Source(index))}restored.current=true;const flush=()=>persist();window.addEventListener('pagehide',flush);document.addEventListener('visibilitychange',flush);void ensureBook();return()=>{persist();window.removeEventListener('pagehide',flush);document.removeEventListener('visibilitychange',flush)}},[ensureBook,persist]);
 useEffect(()=>{current.current={time,rate,mode};if(audio.current)audio.current.playbackRate=rate},[time,rate,mode]);
 useEffect(()=>{if(restored.current)persist()},[rate,mode,persist]);
 function open(){if(!book&&!loading)void ensureBook()}
 function library(){audio.current?.pause();persist();onBack()}
 function streamIndex(next:number){return floorIndex(metadata.markers,next,c=>c.start)}
 function seek(next:number){next=Math.max(0,Math.min(metadata.duration,next));current.current.time=next;setTime(next);if(r2Streaming){const index=streamIndex(next),start=metadata.markers[index]?.start||0;if(index!==streamSegment){audioReady.current=false;streamOffset.current=start;pendingLocalSeek.current=next-start;setStreamSegment(index);setAudioSource(r2Source(index))}else if(audio.current){audio.current.currentTime=Math.max(0,next-start)}}else if(audio.current)audio.current.currentTime=next;persist()}
 async function toggle(){const media=audio.current;if(!media)return;if(!media.paused){media.pause();return}const start=pageRef.current.start;setError('');if(Number.isFinite(start)){if(r2Streaming){const changingSegment=streamIndex(start)!==streamSegment;pendingPlay.current=changingSegment;seek(start);if(changingSegment)return}else seek(start)}try{await media.play()}catch{setError('Playback could not start. Tap Play to try again.')}}
 useEffect(()=>{if(!reading)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.code!=='Space'||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||event.defaultPrevented)return;const target=event.target as HTMLElement;if(chaptersOpen||target.closest('input,textarea,select,button,a,[contenteditable="true"],[role="slider"],[role="combobox"],[role="dialog"],[role="menu"]'))return;event.preventDefault();if(event.repeat)return;if(!book||error||!audio.current)return;if(!audio.current.paused)audio.current.pause();else{setError('');void audio.current.play().catch(()=>setError('Playback could not start. Tap Play to try again.'))}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[reading,book,error,chaptersOpen]);
 const chapterIndex=book?floorIndex(book.chapters,time,c=>c.start):0;
 const markerIndex=floorIndex(metadata.markers,time,c=>c.start),marker=metadata.markers[markerIndex];
 const reportPage=useCallback((chapterIndex:number,page:number,start:number)=>{pageRef.current={chapterIndex,page,start}},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const tool of [{name:'open_book',description:'Open the current book in the reader.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async(input:Record<string,unknown>)=>{if(Object.keys(input).length)throw Error('No arguments accepted');open();await new Promise(r=>setTimeout(r,0));return{book:metadata.id,view:'reader'}}},{name:'seek_book',description:'Seek the audiobook to a source-audio timestamp in seconds.',inputSchema:{type:'object',properties:{seconds:{type:'number',minimum:0,maximum:metadata.duration}},required:['seconds'],additionalProperties:false},execute:async(input:{seconds:number})=>{if(!Number.isFinite(input.seconds)||input.seconds<0||input.seconds>metadata.duration)throw Error('Invalid seconds');seek(input.seconds);await new Promise(r=>setTimeout(r,0));return{seconds:input.seconds}}}]){try{Promise.resolve(context.registerTool({...tool,annotations:{readOnlyHint:false}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort()},[book]);
 return <>
 <audio ref={audio} crossOrigin="anonymous" src={audioSource||undefined} preload="metadata" onEmptied={()=>{audioReady.current=false}} onLoadedMetadata={()=>{if(audio.current){const local=pendingLocalSeek.current??(r2Streaming?current.current.time-(streamOffset.current||0):current.current.time);audio.current.currentTime=Math.max(0,local);pendingLocalSeek.current=null;audio.current.playbackRate=rate;audioReady.current=true;if(pendingPlay.current){pendingPlay.current=false;void audio.current.play().catch(()=>setError('Playback could not start. Tap Play to try again.'))}}}} onTimeUpdate={()=>{if(!reading||!audioReady.current)return;const t=(r2Streaming?(streamOffset.current||0):0)+(audio.current?.currentTime||0);current.current.time=t;setTime(t);if(Date.now()-lastSaved.current>2000){persist();lastSaved.current=Date.now()}}} onPlay={()=>setPlaying(true)} onPause={()=>{setPlaying(false);persist()}} onWaiting={()=>setBuffering(true)} onPlaying={()=>setBuffering(false)} onCanPlay={()=>setBuffering(false)} onEnded={()=>{if(r2Streaming&&streamSegment<metadata.markers.length-1){seek(metadata.markers[streamSegment+1].start);pendingPlay.current=true}else{setPlaying(false);persist()}}} onError={()=>{if(reading)setError(r2Streaming?'Audio could not load from Cloudflare. Try again.':'Audio could not load from Google Drive. Try again.')}}/>
 <main className="reader-shell"><header className="reader-header"><button aria-label="Library" className="back-button" onClick={library}><ChevronLeft size={24}/><span>Library</span></button><div className="reader-book-title"><strong>{metadata.title}</strong><span>{metadata.author}</span><small>{marker.title}</small></div><div className="header-reading-controls"><div className="highlight-controls"><span>Highlight</span><ToggleGroup value={[mode]} onValueChange={v=>{if(v[0]==="word"||v[0]==="sentence")setMode(v[0])}} className="highlight-toggle" aria-label="Highlight mode"><ToggleGroupItem value="word" aria-label="Word highlighting">Word</ToggleGroupItem><ToggleGroupItem value="sentence" aria-label="Sentence highlighting">Sentence</ToggleGroupItem></ToggleGroup></div></div><Sheet open={chaptersOpen} onOpenChange={setChaptersOpen}><SheetTrigger aria-label="Chapters" className="chapters-trigger"><List size={19}/><span>Chapters</span></SheetTrigger><SheetContent side="right" className="chapter-sheet"><SheetHeader><SheetTitle>Chapters</SheetTitle></SheetHeader><nav className="chapter-list">{metadata.markers.map((c,i)=><button key={i} className={i===markerIndex?'selected':''} onClick={()=>{seek(Math.min(metadata.duration,c.start+0.1));setChaptersOpen(false)}}><span>{c.title}</span><span>{i===markerIndex?<Headphones size={15}/>:clock(c.start)}</span></button>)}</nav></SheetContent></Sheet></header>
 <div className="reading-area">{error&&!book?<div role="alert" className="reader-message"><p>{error}</p><button onClick={()=>{setError('');audio.current?.load();void ensureBook()}}>Try again</button></div>:loading||!book?<div className="reader-message" role="status"><LoaderCircle className="spin"/><p>Loading book…</p></div>:<ReadingPage coverURL={metadata.cover} book={book} chapterIndex={chapterIndex} time={time} rate={rate} onRateChange={setRate} mode={mode} playing={playing} buffering={buffering} audio={audio} audioReady={audioReady} streamOffset={streamOffset} r2Streaming={r2Streaming} seek={seek} onPlayPage={start=>{pageRef.current.start=start;void toggle()}} onPageChange={reportPage}/>}</div>
 {error&&book&&<div role="alert" className="playback-error"><span>{error}</span><button onClick={()=>{setError('');setBuffering(false);audio.current?.load()}}>Try again</button></div>}
 </main>
 </>
}
function ReadingPage({coverURL,book,chapterIndex,time,rate,onRateChange,mode,playing,buffering,audio,audioReady,streamOffset,r2Streaming,seek,onPlayPage,onPageChange}:{coverURL:string;book:Book;chapterIndex:number;time:number;rate:number;onRateChange:(rate:number)=>void;mode:'sentence'|'word';playing:boolean;buffering:boolean;audio:React.RefObject<HTMLAudioElement|null>;audioReady:React.RefObject<boolean>;streamOffset:React.RefObject<number>;r2Streaming:boolean;seek:(t:number)=>void;onPlayPage:(start:number)=>void;onPageChange:(chapterIndex:number,page:number,start:number)=>void}){
 const viewport=useRef<HTMLDivElement>(null),article=useRef<HTMLElement>(null),geometry=useRef<{nodes:HTMLElement[];pages:number[];starts:number[];width:number}>({nodes:[],pages:[],starts:[],width:0});const [page,setPage]=useState(0),[pageCount,setPageCount]=useState(1),[layout,setLayout]=useState(0),[showBookRemaining,setShowBookRemaining]=useState(false),[speedOpen,setSpeedOpen]=useState(false);const timeRef=useRef(time);useEffect(()=>{timeRef.current=time},[time]);const chapter=book.chapters[chapterIndex];const cover=time>=book.creditsStart;const introduction=Boolean(book.audioOnlyIntroduction&&time<book.introEnd);
 const chapterRemaining=Math.max(0,chapter.end-time)/rate;const bookRemaining=Math.max(0,book.duration-time)/rate;
 const speeds=[.75,1,1.25,1.5,1.75,2];

 useEffect(()=>{setPage(0)},[chapterIndex]);
 useLayoutEffect(()=>{const el=article.current,view=viewport.current;if(!el||!view)return;let timer:ReturnType<typeof setTimeout>;function measure(){if(!el||!view)return;el.style.transition='none';el.style.transform='none';const width=view.clientWidth;el.style.columnWidth=`${width}px`;const nodes=Array.from(el.querySelectorAll<HTMLElement>('.word'));const base=el.getBoundingClientRect().left;const pages=nodes.map(n=>Math.max(0,Math.floor((n.getBoundingClientRect().left-base+1)/(width+64))));const starts:number[]=[];pages.forEach((p,i)=>{if(starts[p]===undefined)starts[p]=i});geometry.current={nodes,pages,starts,width};setPageCount(Math.max(1,starts.length));setLayout(n=>n+1)}measure();const observer=new ResizeObserver(()=>{clearTimeout(timer);timer=setTimeout(measure,50)});observer.observe(view);return()=>{observer.disconnect();clearTimeout(timer)}},[chapter]);
 useEffect(()=>{
  let frame=0,lastWord=-1,lastSentence=-1,lastPage=-1;
  let highlightedWord:HTMLElement|null=null;
  let highlightedSentence:HTMLElement[]=[];
  const clearClassHighlights=()=>{
   highlightedWord?.classList.remove('active-word');
   highlightedWord=null;
   for(const node of highlightedSentence)node.classList.remove('active-word');
   highlightedSentence=[];
  };
  const el=article.current;if(!el)return;
  const g=geometry.current;
  const update=()=>{
   const t=playing&&audioReady.current&&audio.current?audio.current.currentTime+(r2Streaming?streamOffset.current:0):timeRef.current;
   const word=floorIndex(chapter.cues,t,c=>c[0]);
   let p=g.pages[word]||0;
   const next=g.starts[p+1];
   if(playing&&next!==undefined&&chapter.cues[next][0]-t<=.18*(audio.current?.playbackRate||1))p++;
   if(lastPage!==p){el.style.transition=playing?'transform 180ms ease-out':'none';el.style.transform=`translateX(${-p*(g.width+64)}px)`;setPage(p);const startIndex=g.starts[p]??word;onPageChange(chapterIndex,p,chapter.cues[startIndex]?.[0]??chapter.start);lastPage=p}
   if(chapter.spoken===false||t<chapter.cues[0][0]||t>=book.creditsStart){if(lastWord!==-1){(CSS as any).highlights?.delete('sentence');(CSS as any).highlights?.delete('spoken');clearClassHighlights();el.dataset.activeWord='-1';lastWord=-1;lastSentence=-1}if(playing)frame=requestAnimationFrame(update);return}
   const si=floorIndex(chapter.sentences,word,s=>s[0]);
   if(lastWord!==word||lastSentence!==si){
    el.dataset.activeWord=String(word);
    const css=CSS as any;
    if(mode==='word'){
     css.highlights?.delete('sentence');css.highlights?.delete('spoken');
     clearClassHighlights();
     highlightedWord=g.nodes[word]??null;
     highlightedWord?.classList.add('active-word');
    }else if(css.highlights){
     clearClassHighlights();
     const [a,b]=chapter.sentences[si],first=g.nodes[a],last=g.nodes[b-1];
     if(first&&last){const r=new Range();r.setStartBefore(first);const nextNode=g.nodes[b];if(nextNode&&last.closest('p,li,blockquote,h1,h2,h3')===nextNode.closest('p,li,blockquote,h1,h2,h3')){r.setEndBefore(nextNode);trimNextOpeningQuote(r,last,nextNode)}else{const block=last.closest('p,li,blockquote,h1,h2,h3');if(block)r.setEnd(block,block.childNodes.length);else r.setEndAfter(last)}css.highlights.set('sentence',new (window as any).Highlight(r));css.highlights.delete('spoken')}
    }else{
     clearClassHighlights();
     for(let i=chapter.sentences[si][0];i<chapter.sentences[si][1];i++){const node=g.nodes[i];if(node){node.classList.add('active-word');highlightedSentence.push(node)}}
    }
    lastWord=word;lastSentence=si;
   }
   if(playing)frame=requestAnimationFrame(update);
  };
  update();
  return()=>{cancelAnimationFrame(frame);clearClassHighlights();(CSS as any).highlights?.delete('sentence');(CSS as any).highlights?.delete('spoken')};
 },[chapter,mode,playing,layout,audio,audioReady,streamOffset,r2Streaming,book.creditsStart,chapterIndex,onPageChange]);
 function turn(delta:number){if(introduction){if(delta>0)seek(book.chapters[0].start);return}const target=page+delta;const start=geometry.current.starts[target];if(start!==undefined){const startTime=chapter.cues[start][0];setPage(target);onPageChange(chapterIndex,target,startTime);seek(startTime)}else if(delta<0&&chapterIndex>0){setPage(0);onPageChange(chapterIndex-1,0,book.chapters[chapterIndex-1].start);seek(book.chapters[chapterIndex-1].start)}else if(delta>0&&chapterIndex<book.chapters.length-1){setPage(0);onPageChange(chapterIndex+1,0,book.chapters[chapterIndex+1].start);seek(book.chapters[chapterIndex+1].start)}}
 useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{if(event.key!=='ArrowLeft'&&event.key!=='ArrowRight')return;const target=event.target as HTMLElement;if(target.closest('input,textarea,select,button,a,[contenteditable="true"],[role="slider"],[role="combobox"],[role="dialog"],[role="menu"]'))return;event.preventDefault();turn(event.key==='ArrowRight'?1:-1)};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[page,chapterIndex,chapter,introduction]);
 function playCurrentPage(){const startIndex=geometry.current.starts[page];const start=chapter.cues[startIndex??0]?.[0];if(Number.isFinite(start))onPlayPage(start)}
 function seekWord(event:React.MouseEvent){const word=(event.target as HTMLElement).closest<HTMLElement>('[data-word]');if(!word||!article.current?.contains(word))return;const index=Number(word.dataset.word);if(chapter.cues[index])seek(chapter.cues[index][0]);}
 return <div className="page-layout"><div onClick={seekWord} className="paper-window" ref={viewport} style={{visibility:cover||introduction?'hidden':'visible'}}><BookText ref={article} html={chapter.html}/></div>{introduction&&<div className="cover-page" role="status"><span>Audio-only introduction</span></div>}{cover&&<div className="cover-page"><DriveCover src={coverURL} alt={`${book.title} cover`}/><span>{time<book.introEnd?'Opening credits':'End credits'}</span></div>}<button className="edge-navigation edge-previous" aria-label="Previous page" onClick={()=>turn(-1)} disabled={cover||introduction||(page===0&&chapterIndex===0)}><ChevronLeft size={22}/></button><button className="edge-navigation edge-next" aria-label="Next page" onClick={()=>turn(1)} disabled={cover||(page===pageCount-1&&chapterIndex===book.chapters.length-1)}><ChevronRight size={22}/></button><div className="page-navigation"><button className="play-button page-play-button" aria-keyshortcuts="Space" onClick={playCurrentPage} aria-label={playing?'Pause':'Play page'} disabled={cover||introduction}>{buffering&&playing?<LoaderCircle size={22} className="spin"/>:playing?<Pause size={22} fill="currentColor"/>:<Play size={22} fill="currentColor"/>}</button></div><button className="reader-progress" onClick={()=>setShowBookRemaining(value=>!value)} aria-label={`Show ${showBookRemaining?'chapter':'book'} time remaining`}><span className="reader-progress-track"><span style={{width:`${Math.min(100,Math.max(0,(time-(showBookRemaining?0:chapter.start))/((showBookRemaining?book.duration:chapter.end)- (showBookRemaining?0:chapter.start))*100))}%`}}/></span><span className="reader-progress-label"><span>{clock(chapterRemaining)} chapter</span><span>{clock(bookRemaining)} book</span></span></button><div className="speed-picker"><button className="speed-button" onClick={()=>setSpeedOpen(value=>!value)} aria-expanded={speedOpen} aria-haspopup="listbox" aria-label={`Playback speed ${rate} times`}>{rate}×</button>{speedOpen&&<div className="speed-menu" role="listbox" aria-label="Playback speed">{speeds.map(speed=><button key={speed} role="option" aria-selected={speed===rate} className={speed===rate?'selected':''} onClick={()=>{onRateChange(speed);setSpeedOpen(false)}}>{speed}×</button>)}</div>}</div></div>
}

function trimNextOpeningQuote(range:Range,last:HTMLElement,next:HTMLElement){
 const gap=new Range();gap.setStartAfter(last);gap.setEndBefore(next);
 const text=gap.toString(),trimmed=text.replace(/\s+[“‘"]\s*$/,'');if(trimmed.length===text.length)return;
 const walker=document.createTreeWalker(gap.commonAncestorContainer,NodeFilter.SHOW_TEXT);let remaining=trimmed.length,node:Node|null;
 while((node=walker.nextNode())){if(!gap.intersectsNode(node))continue;const length=node.textContent?.length||0;if(remaining<=length){range.setEnd(node,remaining);return}remaining-=length}
}
const BookText=memo(function BookText({html,ref}:{html:string;ref:React.RefObject<HTMLElement|null>}){return <article ref={ref} className="epub-page" dangerouslySetInnerHTML={{__html:html}}/>});
