#!/usr/bin/env python3
"""Generate app/dark.css: a dark override of every colour in app/globals.css.

Re-run after editing colours in globals.css:  python3 scripts/gen-dark-css.py
Lightness is flipped (keeping hue and saturation), so images are never touched.
"""
import colorsys, re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / 'app/globals.css').read_text()
src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)
PREFIX = 'html[data-theme=dark]'
COLOR = re.compile(r'#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b|rgba?\([^)]*\)')
SHADOW = ('box-shadow', 'text-shadow')

def parse_color(t):
    if t.startswith('#'):
        h = t[1:]
        if len(h) == 3: h = ''.join(ch * 2 for ch in h)
        r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
        a = int(h[6:8], 16) / 255 if len(h) == 8 else 1
        return r, g, b, a
    n = [float(x) for x in re.findall(r'[\d.]+', t)]
    return n[0] / 255, n[1] / 255, n[2] / 255, n[3] if len(n) > 3 else 1

def flip(t, shadow=False):
    r, g, b, a = parse_color(t)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    if shadow and l <= .5: return t
    chroma = .4 * s * (1 - abs(2 * l - 1))  # keep hue but mute the tint so darks read as neutral black
    l = .02 + .90 * (1 - l)
    s = min(1, chroma / max(.001, 1 - abs(2 * l - 1)))
    r, g, b = (round(x * 255) for x in colorsys.hls_to_rgb(h, l, s))
    return f'rgba({r},{g},{b},{round(a, 3)})' if a < 1 else f'rgb({r},{g},{b})'

def blocks(text):
    i, out = 0, []
    while i < len(text):
        j = text.find('{', i)
        if j < 0: break
        depth, k = 1, j + 1
        while depth:
            depth += {'{': 1, '}': -1}.get(text[k], 0); k += 1
        out.append((text[i:j].strip(), text[j + 1:k - 1])); i = k
    return out

def decls(body):
    parts, cur, depth = [], '', 0
    for ch in body:
        depth += (ch == '(') - (ch == ')')
        if ch == ';' and depth == 0: parts.append(cur); cur = ''
        else: cur += ch
    parts.append(cur)
    return [p.split(':', 1) for p in parts if ':' in p]

def dark_decls(body):
    out = []
    for prop, val in decls(body):
        prop, val = prop.strip(), val.strip()
        if prop.startswith('--') or not COLOR.search(val): continue
        out.append(f'{prop}:{COLOR.sub(lambda m: flip(m.group(0), prop in SHADOW), val)}')
    return out

def walk(items):
    css = ''
    for sel, body in items:
        if sel.startswith('@'):
            if sel.startswith('@media'):
                inner = walk(blocks(body))
                if inner: css += f'{sel}{{{inner}}}\n'
            continue
        if sel == ':root':
            v = [f'{p.strip()}:{COLOR.sub(lambda m: flip(m.group(0)), x.strip())}' for p, x in decls(body) if p.strip().startswith('--') and COLOR.search(x)]
            css += f'{PREFIX}{{{";".join(v)};color-scheme:dark}}\n'
            continue
        d = dark_decls(body)
        if d:
            sels = ','.join(f'{PREFIX} {s.strip()}' for s in sel.split(','))
            css += f'{sels}{{{";".join(d)}}}\n'
    return css

(root / 'app/dark.css').write_text('/* Generated by scripts/gen-dark-css.py - do not edit by hand. */\n' + walk(blocks(src)))
